[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = "0.2.2"
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = { version = "0.1.17" }
axum = "0.8.1"
